package com.campusfest.backend.judging;
import com.campusfest.backend.competition.*; import com.campusfest.backend.entity.*; import com.campusfest.backend.registration.*; import com.campusfest.backend.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class JudgingService{private final CompetitionRepository competitions;private final JudgeAssignmentRepository assignments;private final ScoringCriterionRepository criteria;private final EvaluationRepository evaluations;private final CriterionScoreRepository criterionScores;private final UserRepository users;private final RegistrationRepository registrations;public JudgingService(CompetitionRepository c,JudgeAssignmentRepository a,ScoringCriterionRepository cr,EvaluationRepository e,CriterionScoreRepository cs,UserRepository u,RegistrationRepository r){competitions=c;assignments=a;criteria=cr;evaluations=e;criterionScores=cs;users=u;registrations=r;}
 private User user(String email){return users.findByEmailIgnoreCase(email).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found"));} private Competition comp(Long id){return competitions.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Competition not found"));} private void manage(Competition c,User u){if(u.getRole()!=Role.ADMIN&&!c.getCreatedBy().getId().equals(u.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Not allowed");}
 @Transactional public CriterionResponse addCriterion(Long cid,CriterionRequest r,String email){Competition c=comp(cid);manage(c,user(email));ScoringCriterion x=new ScoringCriterion();x.setCompetition(c);x.setName(r.getName().trim());x.setDescription(r.getDescription());x.setMaxScore(r.getMaxScore());x.setSortOrder(r.getSortOrder()==null?0:r.getSortOrder());return CriterionResponse.from(criteria.save(x));}
 public List<CriterionResponse> criteria(Long cid){return criteria.findByCompetitionIdOrderBySortOrderAscIdAsc(cid).stream().map(CriterionResponse::from).toList();}
 @Transactional public JudgeAssignmentResponse assign(Long cid,Long judgeId,String email){Competition c=comp(cid);manage(c,user(email));User j=users.findById(judgeId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Judge not found"));if(j.getRole()!=Role.JUDGE)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"User is not a judge");if(assignments.existsByCompetitionIdAndJudgeId(cid,judgeId))throw new ResponseStatusException(HttpStatus.CONFLICT,"Judge already assigned");JudgeAssignment a=new JudgeAssignment();a.setCompetition(c);a.setJudge(j);return JudgeAssignmentResponse.from(assignments.save(a));}
 public List<JudgeAssignmentResponse> assignments(Long cid){return assignments.findByCompetitionId(cid).stream().map(JudgeAssignmentResponse::from).toList();}
 public List<JudgeAssignmentResponse> myCompetitions(String email){User j=user(email);if(j.getRole()!=Role.JUDGE)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Judge access required");return assignments.findByJudgeId(j.getId()).stream().map(JudgeAssignmentResponse::from).toList();}
 @Transactional public EvaluationResponse submit(Long cid,EvaluationRequest r,String email){User j=user(email);if(j.getRole()!=Role.JUDGE)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Judge access required");Competition c=comp(cid);if(!assignments.existsByCompetitionIdAndJudgeId(cid,j.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Judge is not assigned");if(c.getStatus()!=CompetitionStatus.OPEN)throw new ResponseStatusException(HttpStatus.CONFLICT,"Competition is not open for judging");Registration reg=registrations.findById(r.registrationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Registration not found"));if(reg.getStatus()!=RegistrationStatus.ACTIVE||!reg.getEvent().getId().equals(c.getEvent().getId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Participant is not eligible");if(evaluations.existsByJudgeIdAndRegistrationId(j.getId(),reg.getId()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Evaluation already submitted");List<ScoringCriterion> expected=criteria.findByCompetitionIdOrderBySortOrderAscIdAsc(cid);if(r.scores().size()!=expected.size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"All criteria must be scored exactly once");Map<Long,Integer> supplied=new HashMap<>();for(CriterionScoreInput s:r.scores()){if(supplied.put(s.criterionId(),s.score())!=null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Duplicate criterion");}int total=0;Evaluation e=new Evaluation();e.setCompetition(c);e.setRegistration(reg);e.setJudge(j);for(ScoringCriterion criterion:expected){Integer score=supplied.get(criterion.getId());if(score==null||score<0||score>criterion.getMaxScore())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid criterion score");total+=score;}e.setTotalScore(total);e=evaluations.save(e);for(ScoringCriterion criterion:expected){CriterionScore cs=new CriterionScore();cs.setEvaluation(e);cs.setCriterion(criterion);cs.setScore(supplied.get(criterion.getId()));criterionScores.save(cs);}return new EvaluationResponse(e.getId(),cid,reg.getId(),j.getId(),total,e.getSubmittedAt());}
 public List<EvaluationResponse> results(Long cid){return evaluations.findByCompetitionId(cid).stream().map(e->new EvaluationResponse(e.getId(),e.getCompetition().getId(),e.getRegistration().getId(),e.getJudge().getId(),e.getTotalScore(),e.getSubmittedAt())).toList();}
}
