import { useEffect, useState } from 'react'
import jsQR from 'jsqr'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'
async function api(path, options = {}) {
  const token = localStorage.getItem('campusfest_admin_token')
  const res = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(options.headers || {}) } })
  if (!res.ok) { let m = 'Request failed'; try { const j = await res.json(); m = j.detail || j.message || m } catch {}; throw Error(m) }
  return res.status === 204 ? null : res.json()
}
const nav = [['events','Events'],['registrations','Registrations'],['lost','Lost & Found']]

export default function App() {
  const [admin,setAdmin]=useState(()=>JSON.parse(localStorage.getItem('campusfest_admin_user')||'null'))
  const [page,setPage]=useState('events'), [events,setEvents]=useState([]), [lost,setLost]=useState([]), [notice,setNotice]=useState(''), [editing,setEditing]=useState(null), [selectedEvent,setSelectedEvent]=useState(null)
  const load=async()=>{try{const [e,l]=await Promise.all([api('/events/all'),api('/admin/lost-found')]);setEvents(e);setLost(l)}catch(e){setNotice(e.message)}}
  useEffect(()=>{if(admin)load()},[admin])
  if(!admin)return <Login onLogin={u=>{setAdmin(u);localStorage.setItem('campusfest_admin_user',JSON.stringify(u));localStorage.setItem('campusfest_admin_token',u.token)}}/>
  const logout=()=>{localStorage.removeItem('campusfest_admin_user');localStorage.removeItem('campusfest_admin_token');setAdmin(null)}
  return <div className="app"><aside><div className="brand"><b>CampusFest</b><span>Admin Panel</span></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}>{label}</button>)}</nav><button className="logout" onClick={logout}>Logout</button></aside><main><header><div><span className="eyebrow">ADMIN PANEL</span><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  {page==='events'&&<Events events={events} edit={setEditing} newEvent={()=>setEditing({})} load={load} notice={setNotice} openRegs={id=>{setSelectedEvent(id);setPage('registrations')}}/>}
  {page==='registrations'&&<Registrations events={events} selectedEvent={selectedEvent} setSelectedEvent={setSelectedEvent}/>}
  {page==='lost'&&<LostAdmin rows={lost} load={load} notice={setNotice}/>}
  {editing&&<EventForm event={editing.id?editing:null} close={()=>setEditing(null)} load={load} notice={setNotice}/>}
  </main></div>
}

function Login({onLogin}){const[u,setU]=useState(''),[p,setP]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setErr('');setBusy(true);try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const j=await r.json();if(!r.ok)throw Error(j.detail||'Invalid credentials');if(j.role!=='ADMIN')throw Error('Administrator access required');onLogin(j)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <div className="capAuth"><div className="capLogin"><div className="capHead"><div className="capMark">CF</div><div><b>CampusFest</b><span>Admin Panel</span></div></div><div className="capRule"/><span className="badge">ADMIN LOGIN</span><h1>Sign in</h1><p className="capHint">Manage events, registrations and entry verification.</p><form onSubmit={submit}><label>Admin ID<input autoComplete="username" required value={u} onChange={e=>setU(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={p} onChange={e=>setP(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Login'}</button></form></div></div>}


function Events({events,edit,newEvent,load,notice,openRegs}){const remove=async id=>{if(!confirm('Delete this event?'))return;try{await api('/events/'+id,{method:'DELETE'});notice('Event deleted.');load()}catch(e){notice(e.message)}};const toggle=async e=>{try{await api('/events/'+e.id+'/'+(e.status==='PUBLISHED'?'close':'reopen'),{method:'POST'});notice(e.status==='PUBLISHED'?'Registration closed.':'Registration reopened.');load()}catch(x){notice(x.message)}};return <section className="content"><div className="toolbar"><button className="primary" onClick={newEvent}>+ Post Event</button></div><div className="eventList">{events.map(e=><article className="adminEvent" key={e.id}>{e.posterData?<img src={e.posterData} alt="Poster"/>:<div className="noPoster">No poster</div>}<div><div className="badges"><span className={'badge '+e.status.toLowerCase()}>{e.status}</span></div><h2>{e.title}</h2><p>{e.description}</p></div><div className="actions"><button className="outline" onClick={()=>edit(e)}>Edit</button><button className="outline" onClick={()=>openRegs(e.id)}>Registrations</button>{e.status!=='DRAFT'&&<button className="outline" onClick={()=>toggle(e)}>{e.status==='PUBLISHED'?'Close Registration':'Reopen Registration'}</button>}<button className="danger" onClick={()=>remove(e.id)}>Delete</button></div></article>)}</div>{!events.length&&<div className="empty">No events.</div>}</section>}


function EventForm({event,close,load,notice}){const[form,setForm]=useState({title:event?.title||'',description:event?.description||'',posterData:event?.posterData||'',status:event?.status||'PUBLISHED'});const change=(k,v)=>setForm(f=>({...f,[k]:v}));const file=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2500000){notice('Poster must be 2.5 MB or smaller.');return}const r=new FileReader();r.onload=()=>change('posterData',r.result);r.readAsDataURL(f)};const submit=async e=>{e.preventDefault();try{await api(event?'/events/'+event.id:'/events',{method:event?'PUT':'POST',body:JSON.stringify(form)});notice(event?'Event updated.':'Event posted.');close();load()}catch(x){notice(x.message)}};return <div className="modal"><div className="modalCard"><button className="close" onClick={close}>×</button><span className="badge">{event?'EDIT EVENT':'POST EVENT'}</span><h2>{event?'Edit Event':'Post New Event'}</h2><form onSubmit={submit}><label>Event name<input required value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>Description<textarea required value={form.description} onChange={e=>change('description',e.target.value)}/></label><label>Poster<input type="file" accept="image/png,image/jpeg,image/webp" onChange={file}/></label>{form.posterData&&<img className="preview" src={form.posterData} alt="Poster preview"/>}<label>Initial status<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="PUBLISHED">Open registration</option><option value="DRAFT">Draft</option><option value="CLOSED">Closed registration</option></select></label><div className="formActions"><button type="button" className="outline" onClick={close}>Cancel</button><button className="primary">{event?'Save Changes':'Post Event'}</button></div></form></div></div>}

function Registrations({rows}){return <section className="content"><div className="table"><div className="thead"><b>Student</b><b>Event</b><b>Status</b><b>Registered</b></div>{rows.map(r=><div className="tr" key={r.id}><span>{r.name}<small>{r.studentEmail} · {r.phone}</small></span><span>{r.eventTitle}</span><span className="badge">{r.status}</span><span>{new Date(r.registeredAt).toLocaleString()}</span></div>)}</div>{!rows.length&&<div className="empty">No registrations.</div>}</section>}


function LostAdmin({rows,load,notice}){const[claims,setClaims]=useState([]);const loadClaims=async()=>{try{setClaims(await api('/admin/lost-found/claims'))}catch(e){notice(e.message)}};useEffect(()=>{loadClaims()},[]);const resolve=async id=>{try{await api('/admin/lost-found/'+id+'/resolve',{method:'POST'});notice('Report resolved.');load()}catch(e){notice(e.message)}};const claimAction=async(id,action)=>{try{await api('/admin/lost-found/claims/'+id+'/'+action,{method:'POST'});notice(action==='approve'?'Claim approved and item resolved.':'Claim rejected.');loadClaims();load()}catch(e){notice(e.message)}};return <section className="content"><h2 className="sectionTitle">Claims</h2><div className="adminReports">{claims.map(c=><article className="report" key={c.id}><div className="badges"><span className="badge">{c.status}</span></div><h3>{c.fullName}</h3><p><b>College:</b> {c.college} · {c.course} · Year {c.year}</p><p><b>Email:</b> {c.email} · <b>Phone:</b> {c.phone}</p><p><b>Identification:</b> {c.identificationDetails}</p>{c.lostWhenWhere&&<p><b>Lost:</b> {c.lostWhenWhere}</p>}{c.status==='PENDING'&&<div className="actions"><button className="outline" onClick={()=>claimAction(c.id,'reject')}>Reject Claim</button><button className="primary" onClick={()=>claimAction(c.id,'approve')}>Approve &amp; Mark Returned</button></div>}</article>)}</div>{!claims.length&&<div className="empty">No claims.</div>}<h2 className="sectionTitle">Reports</h2><div className="adminReports">{rows.map(r=><article className="report" key={r.id}><div className="badges"><span className="badge">{r.type}</span><span className="badge">{r.status}</span></div><h3>{r.item}</h3><p>{r.description}</p><small>{r.location} · {r.contact}</small>{r.status==='OPEN'&&<button className="outline" onClick={()=>resolve(r.id)}>Mark Resolved</button>}</article>)}</div>{!rows.length&&<div className="empty">No lost &amp; found reports.</div>}</section>}

