import { useEffect, useState } from 'react'
import jsQR from 'jsqr'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'
async function api(path, options = {}) {
  const token = localStorage.getItem('campusfest_admin_token')
  const res = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(options.headers || {}) } })
  if (!res.ok) { let m = 'Request failed'; try { const j = await res.json(); m = j.detail || j.message || m } catch {}; throw Error(m) }
  return res.status === 204 ? null : res.json()
}
const nav = [['dashboard','Dashboard'],['events','Events'],['registrations','Registrations'],['verify','QR Verification'],['lost','Lost & Found']]

export default function App() {
  const [admin,setAdmin]=useState(()=>JSON.parse(localStorage.getItem('campusfest_admin_user')||'null'))
  const [page,setPage]=useState('dashboard'), [data,setData]=useState(null), [events,setEvents]=useState([]), [regs,setRegs]=useState([]), [lost,setLost]=useState([]), [notice,setNotice]=useState(''), [editing,setEditing]=useState(null)
  const load=async()=>{try{const [d,e,r,l]=await Promise.all([api('/admin/dashboard'),api('/events/all'),api('/admin/registrations'),api('/admin/lost-found')]);setData(d);setEvents(e);setRegs(r);setLost(l)}catch(e){setNotice(e.message)}}
  useEffect(()=>{if(admin)load()},[admin])
  if(!admin)return <Login onLogin={u=>{setAdmin(u);localStorage.setItem('campusfest_admin_user',JSON.stringify(u));localStorage.setItem('campusfest_admin_token',u.token)}}/>
  const logout=()=>{localStorage.removeItem('campusfest_admin_user');localStorage.removeItem('campusfest_admin_token');setAdmin(null)}
  return <div className="app"><aside><div className="brand"><b>CampusFest</b><span>Admin Panel</span></div><div className="identity"><span className="badge">ADMIN</span><strong>{admin.username}</strong></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}>{label}</button>)}</nav><button className="logout" onClick={logout}>Logout</button></aside><main><header><div><span className="eyebrow">ADMIN PANEL</span><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  {page==='dashboard'&&<Dashboard data={data} onClose={async id=>{try{await api('/events/'+id+'/close',{method:'POST'});setNotice('Registration closed.');load()}catch(e){setNotice(e.message)}}} />}
  {page==='events'&&<Events events={events} edit={setEditing} newEvent={()=>setEditing({})} load={load} notice={setNotice}/>}
  {page==='registrations'&&<Registrations rows={regs}/>}
  {page==='verify'&&<Verify setNotice={setNotice}/>}
  {page==='lost'&&<LostAdmin rows={lost} load={load} notice={setNotice}/>}
  {editing&&<EventForm event={editing.id?editing:null} close={()=>setEditing(null)} load={load} notice={setNotice}/>}
  </main></div>
}

function Login({onLogin}){const[u,setU]=useState(''),[p,setP]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setErr('');setBusy(true);try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const j=await r.json();if(!r.ok)throw Error(j.detail||'Invalid credentials');if(j.role!=='ADMIN')throw Error('Administrator access required');onLogin(j)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <div className="capAuth"><div className="capLogin"><div className="capHead"><div className="capMark">CF</div><div><b>CampusFest</b><span>Admin Panel</span></div></div><div className="capRule"/><span className="badge">ADMIN LOGIN</span><h1>Sign in</h1><p className="capHint">Manage events, registrations and entry verification.</p><form onSubmit={submit}><label>Admin ID<input autoComplete="username" required value={u} onChange={e=>setU(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={p} onChange={e=>setP(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Login'}</button></form></div></div>}

function Dashboard({data,onClose}){return <section className="content"><div className="stats">{[['events','Events'],['openEvents','Open registrations'],['closedEvents','Closed'],['registrations','Active registrations'],['lostFound','Open lost/found']].map(([k,l])=><div className="stat" key={k}><b>{data?.[k]??'—'}</b><span>{l}</span></div>)}</div><h2 className="sectionTitle">Recent Events</h2><div className="recent">{(data?.recentEvents||[]).map(e=><div className="recentRow" key={e.id}><div><b>{e.title}</b><small>{e.registrations} active registrations</small></div><span className={'badge '+e.status.toLowerCase()}>{e.status}</span>{e.status==='PUBLISHED'&&<button className="outline" onClick={()=>onClose(e.id)}>Close Registration</button>}</div>)}</div>{!data?.recentEvents?.length&&<div className="empty">No events yet.</div>}</section>}

function Events({events,edit,newEvent,load,notice}){const remove=async id=>{if(!confirm('Delete this event?'))return;try{await api('/events/'+id,{method:'DELETE'});notice('Event deleted.');load()}catch(e){notice(e.message)}};const toggle=async e=>{try{await api('/events/'+e.id+'/'+(e.status==='PUBLISHED'?'close':'reopen'),{method:'POST'});notice(e.status==='PUBLISHED'?'Registration closed.':'Registration reopened.');load()}catch(x){notice(x.message)}};return <section className="content"><div className="toolbar"><button className="primary" onClick={newEvent}>+ Post Event</button></div><div className="eventList">{events.map(e=><article className="adminEvent" key={e.id}>{e.posterData?<img src={e.posterData} alt="Poster"/>:<div className="noPoster">No poster</div>}<div><div className="badges"><span className={'badge '+e.status.toLowerCase()}>{e.status}</span></div><h2>{e.title}</h2><p>{e.description}</p></div><div className="actions"><button className="outline" onClick={()=>edit(e)}>Edit</button>{e.status!=='DRAFT'&&<button className="outline" onClick={()=>toggle(e)}>{e.status==='PUBLISHED'?'Close Registration':'Reopen Registration'}</button>}<button className="danger" onClick={()=>remove(e.id)}>Delete</button></div></article>)}</div>{!events.length&&<div className="empty">No events.</div>}</section>}

function EventForm({event,close,load,notice}){const[form,setForm]=useState({title:event?.title||'',description:event?.description||'',posterData:event?.posterData||'',status:event?.status||'PUBLISHED'});const change=(k,v)=>setForm(f=>({...f,[k]:v}));const file=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2500000){notice('Poster must be 2.5 MB or smaller.');return}const r=new FileReader();r.onload=()=>change('posterData',r.result);r.readAsDataURL(f)};const submit=async e=>{e.preventDefault();try{await api(event?'/events/'+event.id:'/events',{method:event?'PUT':'POST',body:JSON.stringify(form)});notice(event?'Event updated.':'Event posted.');close();load()}catch(x){notice(x.message)}};return <div className="modal"><div className="modalCard"><button className="close" onClick={close}>×</button><span className="badge">{event?'EDIT EVENT':'POST EVENT'}</span><h2>{event?'Edit Event':'Post New Event'}</h2><form onSubmit={submit}><label>Event name<input required value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>Description<textarea required value={form.description} onChange={e=>change('description',e.target.value)}/></label><label>Poster<input type="file" accept="image/png,image/jpeg,image/webp" onChange={file}/></label>{form.posterData&&<img className="preview" src={form.posterData} alt="Poster preview"/>}<label>Initial status<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="PUBLISHED">Open registration</option><option value="DRAFT">Draft</option><option value="CLOSED">Closed registration</option></select></label><div className="formActions"><button type="button" className="outline" onClick={close}>Cancel</button><button className="primary">{event?'Save Changes':'Post Event'}</button></div></form></div></div>}

function Registrations({rows}){return <section className="content"><div className="table"><div className="thead"><b>Student</b><b>Event</b><b>Status</b><b>Registered</b></div>{rows.map(r=><div className="tr" key={r.id}><span>{r.name}<small>{r.studentEmail} · {r.phone}</small></span><span>{r.eventTitle}</span><span className="badge">{r.status}</span><span>{new Date(r.registeredAt).toLocaleString()}</span></div>)}</div>{!rows.length&&<div className="empty">No registrations.</div>}</section>}

function Verify({setNotice}){const[file,setFile]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false);const decode=f=>{setFile(f);setResult(null);const img=new Image();img.onload=async()=>{const c=document.createElement('canvas');const s=Math.min(1,1400/Math.max(img.width,img.height));c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height);const code=jsQR(d.data,d.width,d.height);if(!code?.data){setResult({valid:false,message:'QR code could not be read'});return}setBusy(true);try{setResult(await api('/admin/verify?passToken='+encodeURIComponent(code.data)))}catch(e){setNotice(e.message)}finally{setBusy(false)}};img.src=URL.createObjectURL(f)};return <section className="content narrow"><h2>Verify Entry Pass</h2><div className="panel"><label>Upload pass image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&decode(e.target.files[0])}/></label>{file&&<p className="muted">{file.name}</p>}{busy&&<p>Checking pass…</p>}{result&&<div className={'verify '+(result.valid?'valid':'invalid')}><b>{result.valid?'VALID PASS':'INVALID PASS'}</b><span>{result.message}</span>{result.name&&<><span>Participant: {result.name}</span><span>Event: {result.eventTitle}</span><span>Registration: CF-{result.id}</span></>}</div>}</div></section>}

function LostAdmin({rows,load,notice}){const resolve=async id=>{try{await api('/admin/lost-found/'+id+'/resolve',{method:'POST'});notice('Report resolved.');load()}catch(e){notice(e.message)}};return <section className="content"><div className="adminReports">{rows.map(r=><article className="report" key={r.id}><div className="badges"><span className="badge">{r.type}</span><span className="badge">{r.status}</span></div><h3>{r.item}</h3><p>{r.description}</p><small>{r.location} · {r.contact}</small>{r.status==='OPEN'&&<button className="outline" onClick={()=>resolve(r.id)}>Mark Resolved</button>}</article>)}</div>{!rows.length&&<div className="empty">No lost & found reports.</div>}</section>}
