import { useEffect, useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'
const nav = [['events','Events'],['passes','My Passes'],['schedule','Schedule']]

async function api(path, options={}) {
  const token = localStorage.getItem('campusfest_student_token')
  const res = await fetch(API + path, { ...options, headers:{'Content-Type':'application/json', ...(token?{Authorization:`Bearer ${token}`}:{}) , ...(options.headers||{})} })
  if (!res.ok) { let msg='Request failed'; try { const j=await res.json(); msg=j.message||j.error||msg } catch {} throw new Error(msg) }
  return res.status===204 ? null : res.json()
}

export default function App(){
  const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('campusfest_student_user')||'null'))
  const [page,setPage]=useState('events'); const [events,setEvents]=useState([]); const [passes,setPasses]=useState([]); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false)
  const [authMode,setAuthMode]=useState('login')
  const load=async()=>{setLoading(true);try{setEvents(await api('/events')); if(user)setPasses(await api('/registrations/me'))}catch(e){setNotice(e.message)}finally{setLoading(false)}}
  useEffect(()=>{if(user)load()},[user])
  if(!user) return <Auth mode={authMode} setMode={setAuthMode} onLogin={u=>{setUser(u);localStorage.setItem('campusfest_student_user',JSON.stringify(u));localStorage.setItem('campusfest_student_token',u.token)}} />
  const register=async id=>{try{await api(`/registrations/events/${id}`,{method:'POST'});setNotice('Registration confirmed.');await load()}catch(e){setNotice(e.message)}}
  const logout=()=>{localStorage.removeItem('campusfest_student_user');localStorage.removeItem('campusfest_student_token');setUser(null)}
  return <div className="app"><aside><div className="brand"><b>CampusFest</b><span>Student Portal</span></div><div className="identity"><span className="badge">STUDENT</span><strong>{user.name}</strong><small>{user.email}</small></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><i>{id==='events'?'◫':id==='passes'?'▣':'◷'}</i>{label}</button>)}</nav><div className="sideBottom"><span className="badge soft">LIVE</span><button className="logout" onClick={logout}>Sign out</button></div></aside><main><header><div><span className="eyebrow">CAMPUSFEST</span><h1>{page==='events'?'Discover events':page==='passes'?'My passes':'Schedule'}</h1></div><span className="badge">{events.length} PUBLISHED EVENTS</span></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{loading?<div className="empty">Loading live data…</div>:page==='events'?<Events events={events} passes={passes} register={register}/>:page==='passes'?<Passes passes={passes} events={events}/>:<Schedule events={events}/>}</main></div>
}

function Auth({mode,setMode,onLogin}){const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');try{const r=await fetch(API+`/auth/${mode==='login'?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='login'?{email,password}:{name,email,password})});const j=await r.json();if(!r.ok)throw new Error(j.message||'Authentication failed');onLogin(j)}catch(x){setErr(x.message)}};return <div className="auth"><div className="authCard"><div className="brand"><b>CampusFest</b><span>Student Portal</span></div><span className="badge">{mode==='login'?'STUDENT LOGIN':'CREATE STUDENT ACCOUNT'}</span><h1>{mode==='login'?'Welcome back':'Join CampusFest'}</h1><p>{mode==='login'?'Use your registered student account.':'Create a real student account. No demo data is used.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength="8" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary">{mode==='login'?'Sign in':'Create account'}</button></form><button className="textBtn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create a student account':'Already have an account? Sign in'}</button></div></div>}

function Events({events,passes,register}){const ids=new Set(passes.map(p=>p.eventId));return <section className="content"><div className="grid">{events.map(e=><article className="card" key={e.id}>{e.posterData?<img className="poster" src={e.posterData} alt="Event poster"/>:<div className="poster emptyPoster"><span className="badge">NO POSTER</span></div>}<div className="cardBody"><span className="badge">{e.category}</span><h2>{e.title}</h2><p>{e.description}</p><div className="meta"><span>◷ {new Date(e.startTime).toLocaleString()}</span><span>⌖ {e.venue}</span><span>Seats: {e.capacity}</span></div><button disabled={ids.has(e.id)} className={ids.has(e.id)?'success':'primary'} onClick={()=>register(e.id)}>{ids.has(e.id)?'Registered ✓':'Register for event'}</button></div></article>)}</div>{!events.length&&<div className="empty"><h2>No published events yet</h2><p>The administrator has not published an event.</p></div>}</section>}
function Passes({passes,events:_events}){return <section className="content"><div className="grid">{passes.filter(p=>p.status==='ACTIVE').map(p=><div className="card pass" key={p.id}><span className="badge">ACTIVE PASS</span><h2>{p.eventTitle}</h2><p>Registered {new Date(p.registeredAt).toLocaleString()}</p><div className="passCode">REG-{p.id}</div></div>)}</div>{!passes.length&&<div className="empty"><h2>No passes yet</h2><p>Register for a published event and your pass will appear here.</p></div>}</section>}
function Schedule({events}){return <section className="content"><div className="schedule">{events.map(e=><div className="scheduleRow" key={e.id}><span className="badge">{e.category}</span><div><b>{e.title}</b><small>{new Date(e.startTime).toLocaleString()} · {e.venue}</small></div></div>)}</div>{!events.length&&<div className="empty">No schedule is published yet.</div>}</section>}
