import { useEffect, useState } from 'react'
import './App.css'

const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api'
const nav=[['events','Events'],['passes','My Passes'],['schedule','Schedule']]
const PASS_KEY='campusfest_guest_passes'

async function api(path,options={}){
 const res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}})
 if(!res.ok){let msg='Request failed';try{const j=await res.json();msg=j.message||j.error||msg}catch{}throw Error(msg)}
 return res.status===204?null:res.json()
}
function savedTokens(){try{return JSON.parse(localStorage.getItem(PASS_KEY)||'[]')}catch{return[]}}
function saveToken(token){const tokens=[...new Set([...savedTokens(),token])];localStorage.setItem(PASS_KEY,JSON.stringify(tokens));return tokens}

export default function App(){
 const [page,setPage]=useState('events'),[events,setEvents]=useState([]),[passes,setPasses]=useState([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null)
 const load=async()=>{setLoading(true);try{setEvents(await api('/events'));const tokens=savedTokens();const loaded=[];for(const t of tokens){try{loaded.push(await api('/registrations/me?passToken='+encodeURIComponent(t)))}catch{}}setPasses(loaded)}catch(e){setNotice(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const register=async form=>{const r=await api('/registrations/events/'+selected.id,{method:'POST',body:JSON.stringify(form)});saveToken(r.passToken);setPasses(p=>[r,...p]);setSelected(null);setPage('passes');setNotice('Registration confirmed. Your pass is saved on this device.')}
 const cancel=async pass=>{if(!confirm('Cancel this registration?'))return;try{await api('/registrations/me?passToken='+encodeURIComponent(pass.passToken),{method:'DELETE'});setPasses(p=>p.map(x=>x.id===pass.id?{...x,status:'CANCELLED'}:x));setNotice('Registration cancelled.')}catch(e){setNotice(e.message)}}
 return <div className="app"><aside><div className="brand"><b>CampusFest</b><span>Student Portal</span></div><div className="identity"><span className="badge">PUBLIC ACCESS</span><strong>No account required</strong><small>Browse events and register directly.</small></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><i>{id==='events'?'◫':id==='passes'?'▣':'◷'}</i>{label}</button>)}</nav><div className="sideBottom"><span className="badge soft">LIVE DATA</span></div></aside><main><header><div><span className="eyebrow">CAMPUSFEST</span><h1>{page==='events'?'Discover events':page==='passes'?'My passes':'Schedule'}</h1></div><span className="badge">{events.length} PUBLISHED EVENTS</span></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{loading?<div className="empty">Loading live data…</div>:page==='events'?<Events events={events} onRegister={setSelected}/>:page==='passes'?<Passes passes={passes} cancel={cancel}/>:<Schedule events={events}/>} {selected&&<RegistrationForm event={selected} close={()=>setSelected(null)} submit={register}/>}</main></div>
}

function Events({events,onRegister}){return <section className="content"><div className="grid">{events.map(e=><article className="card" key={e.id}>{e.posterData?<img className="poster" src={e.posterData} alt="Event poster"/>:<div className="poster emptyPoster"><span className="badge">NO POSTER</span></div>}<div className="cardBody"><span className="badge">{e.category}</span><h2>{e.title}</h2><p>{e.description}</p><div className="meta"><span>◷ {new Date(e.startTime).toLocaleString()}</span><span>⌖ {e.venue}</span><span>Seats: {e.capacity}</span></div><button className="primary" onClick={()=>onRegister(e)}>Register for event</button></div></article>)}</div>{!events.length&&<div className="empty"><h2>No published events yet</h2><p>The administrator has not published an event.</p></div>}</section>}

function RegistrationForm({event,close,submit}){const [form,setForm]=useState({name:'',college:'',course:'',year:'',email:'',phone:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const change=(k,v)=>setForm(f=>({...f,[k]:v}));const send=async e=>{e.preventDefault();setErr('');setBusy(true);try{await submit(form)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <div className="modal"><div className="modalCard"><button className="close" onClick={close}>×</button><span className="badge">EVENT REGISTRATION</span><h2>{event.title}</h2><p className="muted">No account or password is required. Enter your real details to receive an entry pass.</p><form onSubmit={send} className="formGrid">{[['name','Full name'],['college','College'],['course','Course'],['year','Year'],['email','Email'],['phone','Phone']].map(([k,l])=><label key={k}>{l}<input required type={k==='email'?'email':'text'} value={form[k]} onChange={e=>change(k,e.target.value)}/></label>)}{err&&<div className="error">{err}</div>}<div className="formActions"><button type="button" className="outline" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Registering…':'Confirm registration'}</button></div></form></div></div>}

function Passes({passes,cancel}){return <section className="content"><div className="grid">{passes.filter(p=>p.status==='ACTIVE').map(p=><div className="card pass" key={p.id}><div className="badges"><span className="badge">ACTIVE PASS</span><span className="badge soft">{p.course} · {p.year}</span></div><h2>{p.eventTitle}</h2><p>{p.name} · {p.college}</p><p>Registered {new Date(p.registeredAt).toLocaleString()}</p><div className="passCode">REG-{p.id}</div><button className="outline" onClick={()=>cancel(p)}>Cancel registration</button></div>)}</div>{!passes.filter(p=>p.status==='ACTIVE').length&&<div className="empty"><h2>No passes on this device</h2><p>Register for a published event and your entry pass will appear here.</p></div>}</section>}

function Schedule({events}){return <section className="content"><div className="schedule">{events.map(e=><div className="scheduleRow" key={e.id}><span className="badge">{e.category}</span><div><b>{e.title}</b><small>{new Date(e.startTime).toLocaleString()} · {e.venue}</small></div></div>)}</div>{!events.length&&<div className="empty">No schedule is published yet.</div>}</section>}
