package com.campusfest.backend.competition;
import com.campusfest.backend.entity.User; import com.campusfest.backend.event.Event; import com.campusfest.backend.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class CompetitionService{private final CompetitionRepository competitions; private final EventRepository events; private final UserRepository users; public CompetitionService(CompetitionRepository c,EventRepository e,UserRepository u){competitions=c;events=e;users=u;}
 private User user(String email){return users.findByEmailIgnoreCase(email).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found"));}
 private void adminOrOwner(Competition c,User u){if(u.getRole()!=com.campusfest.backend.entity.Role.ADMIN&&!c.getCreatedBy().getId().equals(u.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Not allowed");}
 @Transactional public CompetitionResponse create(CompetitionRequest r,String email){User u=user(email);Event e=events.findById(r.getEventId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Event not found"));Competition c=new Competition();c.setEvent(e);c.setCreatedBy(u);c.setTitle(r.getTitle().trim());c.setDescription(r.getDescription().trim());c.setStatus(r.getStatus()==null?CompetitionStatus.DRAFT:r.getStatus());return CompetitionResponse.from(competitions.save(c));}
 public List<CompetitionResponse> list(){return competitions.findAllByOrderByCreatedAtDesc().stream().map(CompetitionResponse::from).toList();}
 public Competition get(Long id){return competitions.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Competition not found"));}
 @Transactional public CompetitionResponse update(Long id,CompetitionRequest r,String email){Competition c=get(id);adminOrOwner(c,user(email));Event e=events.findById(r.getEventId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Event not found"));c.setEvent(e);c.setTitle(r.getTitle().trim());c.setDescription(r.getDescription().trim());if(r.getStatus()!=null)c.setStatus(r.getStatus());return CompetitionResponse.from(c);}
 @Transactional public void delete(Long id,String email){Competition c=get(id);adminOrOwner(c,user(email));competitions.delete(c);}
}
